# Generated by Django 2.0.9 on 2018-11-15 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
    ]
